#! /usr/bin/env python

import sys
import itertools

num_modules = int(sys.argv[1])
majority = num_modules/2 + 1

modules = ["zero_%d" % (i) for i in range(num_modules)]

code = []

for combo in itertools.product(modules, repeat=majority):
    if [i for i in combo] == sorted(combo):
        for i, module in enumerate(combo):
            if i > 0 and module == combo[i - 1]:
                break
        else:
            code.append("({0})".format(" & ".join(combo)))

print " | ".join(code)